version: '3.7'
services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - /data/mongo

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '50000:50000'

volumes:
  mongodb_data_container:
